# Generated by Django 4.2.3 on 2023-08-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistika',
            old_name='tolagan_summa',
            new_name='tolangan_summa',
        ),
    ]
