# Generated by Django 4.2.3 on 2023-08-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('dokon', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=30)),
                ('qarz', models.PositiveIntegerField(default=0)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('narx', models.PositiveIntegerField()),
                ('soni', models.CharField(max_length=30)),
                ('olchov', models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('dona', 'dona'), ('block', 'block')], max_length=30)),
                ('sana', models.DateField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
    ]
