# Generated by Django 4.2.3 on 2023-08-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mijoz',
            old_name='dokon',
            new_name='Ism',
        ),
    ]
