# Generated by Django 4.2.3 on 2023-08-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('asosiy', '0002_rename_dokon_mijoz_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='ombor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor'),
        ),
    ]
