# Generated by Django 4.2.3 on 2023-08-03 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('asosiy', '0003_alter_maxsulot_ombor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor'),
        ),
    ]
